version: '2'

services:
  minio:
    container_name: Minio
    command: server /data --console-address ":9090"
    environment:
      - MINIO_ROOT_USER=(enter username)
      - MINIO_ROOT_PASSWORD=(enter password)
    image: quay.io/minio/minio:latest
    ports:
      - '9000:9000'
      - '9090:9090'
    volumes:
      - /docker/minio:/data
    restart: unless-stopped